name: DevSecOps-CI

on:
    push:
        branches: [practice]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yaml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml


        